# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Radius Portal Build (Angular)
permissions:
  contents: write
  pull-requests: write
  repository-projects: write
  pages: write
  id-token: write
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Build and test angular code
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build --if-present
    - run: npm test -- --watch=false --browsers=ChromeHeadless

    - name: Comment Test Coverage
      uses: AthleticNet/comment-test-coverage@1.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        path: coverage/rportal/coverage-summary.json
        title: Karma Test Coverage
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action/linux@v2
      if: always()
      with:
        files: |
          reports/*.xml

