# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Radius Portal Build (Angular)
permissions:   
  contents: read
  pages: write
  id-token: write
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Build and test angular code
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build --if-present
    - run: npm test -- --watch=false --browsers=ChromeHeadless

    - name: Setup Pages
      uses: actions/configure-pages@v2
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        # Upload the coverage directory from the repository
        path: './coverage/rportal'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
#    - name: Coverage report
#      if: always()
#      uses: eleboys/test-coverage-report-action@v1.0.2
#      id: report
#      with:
#        token: ${{ secrets.GITHUB_TOKEN }}
#        path: coverage/rportal/coverage-summary.json
#        title: Karma Test Coverage
#
#    - name: Print the output summary
#      run: echo "Report coverage json ${{ steps.report.outputs.summary }}"

